### ISSUE TITLE
feature: save logs in a data strucure

### ISSUE THREAD

**Issue by polyedre** [eirbot/eirbot2020-2A#1]

**Comment by astralien3000** [comment]
J'ai un peu de mal à comprendre. Sauvegarder les logs dans un MCU ? Y aura pas beaucoup de place en RAM, et je sais pas si ça vaut le coup d'utiliser la flash. Ou tu parles juste d'un ring buffer pour ne pas attendre la comm UART ?

**Comment by polyedre** [comment]
Je veux que les logs soient envoyés au PC depuis la rasp, et sauvegardés dans un fichier et dans un objet, pour pouvoir les traiter en temps réel (les afficher, les trier), et pour pouvoir avoir un historique
Le plus simple serait peut-être de tout écrire dans un fichier et de le lire à chaque fois (tout se passe ici sur le PC, la rasp héberge juste un serveur tcp et envoie des données quand il faut)

**Comment by polyedre** [comment]
J'ai choisi pour l'instant d'enregistrer les logs dans un fichier (nouveau pour chaque session) et dans une liste de dictionnaires avec les clés "time", "tag" et "data".

Avancement :
 - [x] Enregistrer les logs dans un tableau lors de la réception
 - [x] Enregistrer les logs dans un fichier en même temps
 - [x] Passer les logs dans un dictionnaire
