### ISSUE TITLE
Valider le CAN sur Hermes 2

### ISSUE THREAD

**Issue by astralien3000** [eirbot/eirbot2020-2A#4]
Si on l'utilise comme bus de comm, ça pourrait être utile de vérifier qu'il fonctionne !
Cette issue est liée à #2, car le CAN pourrait être le bus support de la comm entre la rasp et les mcu.

**Comment by polyedre** [comment]
Pour l'instant je suis resté sur l'interaction PC/Rasp, c'est quoi les acronymes CAN et mcu ?

D'ailleurs, le code Nucléo n'a toujours pas été ajouté à ce projet

**Comment by Elioty** [comment]
J'ai retrouvé la lib pour driver le CAN sur Hermes 2 / Teensy 3.{1,2} :
https://github.com/PaulStoffregen/FlexCAN

**Comment by astralien3000** [comment]
CAN (Controller Area Network) est un bus de communication série (comme l'UART, I2C, SPI), asynchrone (comme l'UART), half-duplex (comme l'I2C) qui est présent dans le monde de l'automobile.

MCU c'est pour MicroController Unit.

**Comment by astralien3000** [comment]
On ne vas pas forcer d'utiliser du CAN, mais on voulais se donner la possibilité de l'utiliser sur notre carte électronique [Hermes 2](https://github.com/xenomorphales/xenomorphales/issues/66).
On ne l'a cependant pas testé, et on aimerai le faire cette année.

**Comment by polyedre** [comment]
D'accord :)

**Comment by Elioty** [comment]
Testé aujourd'hui avec l'analyseur CAN de Loïc (enfin, de sa boite...) et la lib FlexCAN linkée plus haut, ça fonctionne bien 😃 Devrait-on fermer l'issue ou tu veux essayer avec la lib FlexCAN qui vient avec Teensyduino d'abord ?

**Comment by astralien3000** [comment]
Non, c'est bon, on s'occupera de mettre "à jour" le code quand on testera avec la rasp.

**Comment by astralien3000** [comment]
Pour référence, [voici l'analyseur CAN utilisé](https://www.peak-system.com/PCAN-USB.199.0.html?&L=1&gclid=Cj0KCQjwrMHsBRCIARIsAFgSeI0YhzuCcdY3xJWGk4XIaUuZ9ecshy32NXvoU0vglSpLXhKS-LMl6TUaAqTXEALw_wcB).
