### ISSUE TITLE
Acheter un Hat CAN pour rasp

### ISSUE THREAD

**Issue by astralien3000** [eirbot/eirbot2020-2A#7]
En continuation de #4 qui s'est soldé par un succès, on va passer à la vitesse supérieure en mettant du CAN sur la rasp. Celui sélectionné pour le moment est [ici](https://www.kubii.fr/composants-raspberry-pi/2487-rs485-can-hat-pour-raspberry-pi-kubii-3272496014381.html). J'achèterai une [rasp 4](https://www.kubii.fr/les-cartes-raspberry-pi/2677-nouveau-raspberry-pi-4-modele-b-1gb-2gb-4gb-kubii-3272496298750.html) en même temps.

**Comment by Elioty** [comment]
N'oublie pas le câble USB type C pour alimenter la Rasp 4 😉

**Comment by astralien3000** [comment]
Trop tard ! ><

**Comment by astralien3000** [comment]
Hat reçu ! rasp aussi. On est bon pour tester (#8 )

**Comment by Elioty** [comment]
L'issue est closed mais je poste ça ici, j'ai trouvé le site officiel du HAT avec sa documentation !!
https://www.waveshare.com/rs485-can-hat.htm
